// Generated by CoffeeScript 1.6.2
(function() {
  var TestClass, _main;

  require('../../lib/coffee_stack').patch(__dirname);

  TestClass = (function() {
    function TestClass() {}

    TestClass.prototype.innerError = function() {
      throw new Error(__filename);
    };

    TestClass.prototype.outterErrorWithSourceMap = function() {
      var c;

      c = require('./with_sourcemap');
      return c.run();
    };

    TestClass.prototype.outterErrorWithoutSourceMap = function() {
      var c;

      c = require('./without_sourcemap');
      return c.run();
    };

    return TestClass;

  })();

  exports.run = function(test) {
    var err, k, obj, v;

    obj = new TestClass();
    for (k in obj) {
      v = obj[k];
      try {
        v.apply(obj);
      } catch (_error) {
        err = _error;
        console.log(err.stack);
      }
    }
    return test.done();
  };

  _main = function() {
    var test;

    test = {
      done: function() {
        return console.log("test.done()");
      }
    };
    return exports.run(test);
  };

  if (require.main === module) {
    _main();
  }

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
