// Generated by CoffeeScript 1.6.2
(function() {
  var _run;

  exports.run = function() {
    return _run();
  };

  _run = (function() {
    var location;

    location = __filename;
    return function() {
      throw new Error(location);
    };
  })();

}).call(this);

/*
//@ sourceMappingURL=with_sourcemap.map
*/
